spring:
  application:
    name: ms-tracking
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    config:
      fail-fast: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
